[tool.poetry]
name = "ghost_post"
version = "0.1.0"
description = ""
authors = ["Delvric <mr.tezeno@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "poetry install"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
